apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod-flask-app
commonLabels:
  environment: prod
images:
- name: backend_image
  newName: testimage
  newTag:  "0.2"
resources:
  - "./../base"
namePrefix: prod-